### ISSUE TITLE
JSON Schemas or OpenAPI Spec?

### ISSUE THREAD

**Issue by jonschlinkert** [cohere-ai/cohere-developer-experience#92]
Hi there, I'm not sure if this is the right place to ask, but I've been looking for some kind of official schemas that I can programmatically ingest to keep our API up-to-date. Does cohere publish any kind of schema or spec for the available endpoints?

Thanks!

**Comment by billytrend-cohere** [comment]
Hey @jonschlinkert this is now available in this file: https://github.com/cohere-ai/cohere-developer-experience/blob/main/cohere-openapi.yaml does that fix your issue? Thanks

**Comment by jonschlinkert** [comment]
Yes! Perfect, thank you so much, I really appreciate it!
