### ISSUE TITLE
Incomplete 'tool_plan' Message in Response Body

### ISSUE THREAD

**Issue by jonschlinkert** [cohere-ai/cohere-developer-experience#98]
I'm not sure if this is from a bad yaml conversion or something else. Looks like the `tool_plan` was malformed somehow:

https://github.com/cohere-ai/cohere-developer-experience/blob/976125d7131ddaed15ef590c5ff00706bbd40519/cohere-openapi.yaml#L6980-L7005

**Comment by billytrend-cohere** [comment]
Thanks @jonschlinkert , will get this fixed!

**Comment by jonschlinkert** [comment]
No worries, it happens. I almost didn't catch it myself.

**Comment by billytrend-cohere** [comment]
This is fixed now!
